"""Structured schema for parsed slip fields.

All downstream components — the synth renderer, the OCR pipeline, the LLM
finetune target, and the Streamlit demo — share this schema so the training
labels, the model outputs, and the UI stay in lockstep.

A parsed slip is a `Slip` record. Amounts are in THB (Thai baht) as minor
units (satang) to avoid float drift; the renderer formats them with the
Thai comma-decimal convention at display time.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

Bank = Literal[
    "SCB",       # Siam Commercial Bank
    "KBANK",     # Kasikornbank
    "BBL",       # Bangkok Bank
    "KTB",       # Krungthai Bank
    "BAY",       # Krungsri / Bank of Ayudhya
    "TMB",       # TMBThanachart (TTB)
    "GSB",       # Government Savings Bank
    "PROMPTPAY",  # Interbank QR
    "OTHER",
]

Category = Literal[
    "transfer",
    "food",
    "rent",
    "utilities",
    "salary",
    "refund",
    "shopping",
    "transport",
    "other",
]


class Party(BaseModel):
    """Either a named account holder or a masked account number."""

    name: str | None = None                       # display name ("MR. SIMON Y.")
    account_masked: str | None = None             # e.g. "xxx-x-x1234-x"
    bank: Bank | None = None                      # issuing bank, when visible
    phone: str | None = None                      # PromptPay phone alias, masked


class Slip(BaseModel):
    """Canonical parsed slip record. All OCR/LLM outputs decode to this."""

    amount_satang: int = Field(ge=0,
        description="Transfer amount in satang (THB × 100) to avoid float drift")
    currency: Literal["THB"] = "THB"

    timestamp: datetime = Field(
        description="Transaction timestamp in the slip's stated timezone (usually Asia/Bangkok)")
    reference_id: str | None = Field(default=None,
        description="Bank-generated transaction reference, when present")

    sender: Party
    receiver: Party

    channel: Bank = Field(
        description="The app/bank the slip was generated by (not necessarily sender's bank)")
    memo: str | None = Field(default=None,
        description="Free-form note the user attached to the transfer")

    category: Category | None = Field(default=None,
        description="Inferred category — populated by the downstream classifier, not the OCR stage")

    @property
    def amount_thb(self) -> float:
        return self.amount_satang / 100.0
